name: carsite-admin-dashboard
services:
  carsite-admin-dashboard:
    container_name: carsite-admin-dashboard
    build:
      context: .
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
