user root;

events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 443 ssl;
        server_name ibetech.online;

        ssl_certificate /etc/letsencrypt/live/ibetech.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ibetech.online/privkey.pem;

        root /dist/carsite-admin-dashboard/browser;

        location / {
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 80;
        server_name ibetech.online;

        return 301 https://$host$request_uri;
    }
}