user root;

events {}

http {
    include /etc/nginx/mime.types;

    server {
        root /dist/carsite-admin-dashboard/browser;

        listen 9500;
        server_name 192.168.1.98;
        location / {
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}